ECommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index.as_view() , name="ShopHome"),
    path('product_detail/<int:pk>', views.product_detail.as_view(),name="product_detail"),
    path('send', views.send , name="send"),
    path('signup', views.signup.as_view() , name="signup"),
    path('login', views.login.as_view() , name="login"),
    path('logout', views.logout.as_view() , name="logout"),
    path('cart_list', views.cart_list , name="cart_list"),
    path('get_data', views.get_data, name='get_data'),
    path('popular_item', views.PopularItemListView.as_view(), name='popular_item'),
    path('newArrivals', views.newArrivals.as_view(), name='newArrivals'),
    path('delete_add_item', views.delete_add_item, name='delete_add_item'),
    path('boys', views.Boys.as_view(), name='boys'),
    path('Electronics', views.Electronics.as_view(), name='Electronics'),
    path('Accessories', views.Accessories.as_view(), name='Accessories'),
    path('girls', views.girls.as_view(), name='girls'),
    path('checkout', views.checkout.as_view(), name='checkout'), 
    path('payment', views.payment, name='payment'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    prod_id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=50,default='')
    subcategory = models.CharField(max_length=50, default='')
    prod_name = models.CharField(max_length=50)
    price = models.IntegerField()
    prod_desc = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to="shop/images",default='')
    def __str__(self):
        return self.prod_name

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255)
    price = models.IntegerField()
    image = models.CharField(max_length=255)
    quantity = models.IntegerField(default=1)
    

class UserAddress(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=50)
    house = models.CharField(max_length=50)
    postalcode = models.CharField(max_length=20)
    zip = models.CharField(max_length=10)
    message_to_seller = models.TextField(blank=True)

shop/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http.response import HttpResponse
from .models import Product
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView ,ListView , FormView , CreateView , DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from .models import CartItem
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
# Create your views here.

class index(ListView):
    model = Product
    template_name = "shop/index1.html"
    context_object_name = "products"


class product_detail(DetailView):
    model = Product
    template_name = "shop/product_detail.html"
    context_object_name = "product_data"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        related_products = Product.objects.filter(category=self.object.category).exclude(prod_id=self.object.prod_id)[:4]
        context['related_products'] = related_products
        return context
 # Use the appropriate login URL
def send(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        product_name = request.POST.get('product_name')
        num = request.POST.get('num')
        product_image = request.POST.get('product_image')
        price = request.POST.get('price')

        # Assuming you have a logged-in user (login_required decorator ensures this)
        user = request.user
        # Try to get the existing cart item, or create a new one if not found
        cart_item, created = CartItem.objects.get_or_create(user=user, product_name=product_name,image=product_image,price = price)

        # If the cart item exists, update the quantity
        if not created:
            cart_item.quantity += int(num)
            cart_item.save()

        response_data = {
            'message': 'Data received and stored in the cart successfully',
            'username': username,
            'product_name': product_name,
            'num': num,
        }

        return JsonResponse(response_data)
    else:
        return JsonResponse({'error': 'Please login to view the cart'})

from django.contrib.auth.forms import UserCreationForm
class signup(CreateView):
    form_class = UserCreationForm
    template_name = "shop/signup.html"  
    success_url = "/login"
    def get(self,request,*args,**kwargs):
        if self.request.user.is_authenticated:
           return redirect("page1.note")
        return super().get(request,*args,**kwargs)

class login(LoginView):
    template_name = "shop/login.html"  
    success_url = "/"
    def get(self, request , *args , **kwargs):
        if self.request.user.is_authenticated:
           return redirect("page1.note")
        return super().get(request,*args,**kwargs)
    
class logout(LogoutView):
    template_name = "shop/logout.html"  
    success_url = "/login"
    
def cart_list(request):
    # Fetch cart items for the logged-in user
    cart_items = CartItem.objects.filter(user=request.user)

    total_items = cart_items.count()

    for item in cart_items:
        item.total = item.price * item.quantity

    context = {
        'cart_items': cart_items,
        'total_items': total_items,
    }
    print("Server Response:", context)
    return render(request, 'shop/cart_list.html', context)

from django.core.serializers import serialize
def get_data(request):
    if request.method == "GET" and request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user)
        total_items = cart_items.count()
        total_price = sum(item.price * item.quantity for item in cart_items)

        # Serialize cart items
        cart_items_serialized = serialize('json', cart_items)

        return JsonResponse({
            "total_items": total_items,
            "total_price": total_price,
            "cart_items": cart_items_serialized,
        }, safe=False)  # Set safe to False to allow serializing lists
    else:
        return JsonResponse({"error": "User not authenticated"}, status=403)
    

def delete_add_item(request):
    if request.method == "POST":
        product_name = request.POST.get("product_name")
        
        if product_name is not None:
            try:
                cart_item = CartItem.objects.get(product_name=product_name)
                cart_item.delete()
                return JsonResponse({"product_name": product_name})
            except CartItem.DoesNotExist:
                return JsonResponse({"error": f"Product with name {product_name} not found"}, status=404)
        else:
            return JsonResponse({"error": "Product name not provided"}, status=400)
    else:
        return JsonResponse({"error": "Invalid request method"}, status=405)


def payment(request):   
    cart_items = CartItem.objects.filter(user = request.user)
    total_price = sum(item.price * item.quantity for item in cart_items)

    return render(request, "shop/payment.html",{"total_price": total_price})
from .models import UserAddress
class checkout(ListView):
    model = CartItem
    template_name = "shop/checkout.html"
    context_object_name = "data"

    def get_queryset(self):
        # Filter CartItem instances for the current user
        return CartItem.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        for item in context["object_list"]:
            item.total = item.price * item.quantity

        total_price = sum(item.price * item.quantity for item in context["data"])
        context["totalPrice"] = total_price
        
        return context
    
    def post(self, request, *args, **kwargs):
    # Extract user address information from the form
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        address = request.POST.get('address')
        city = request.POST.get('city')
        house = request.POST.get('house')
        postalcode = request.POST.get('postalcode')
        zip_code = request.POST.get('zip')
        message_to_seller = request.POST.get('message_to_seller')

        # Create a UserAddress instance and save it to the database
        user_address = UserAddress.objects.create(
            firstname=firstname,
            lastname=lastname,
            phone=phone,
            email=email,
            address=address,
            city=city,
            house=house,
            postalcode=postalcode,
            zip=zip_code,
            message_to_seller=message_to_seller
        )

        # Additional logic if needed

        # Clear the user's cart after completing the checkout

        return redirect('payment')
    

class PopularItemListView(ListView):
    model = CartItem  # Assuming you have a Product model
    template_name = "shop/popular_item.html"
    context_object_name = "data"

class newArrivals(ListView):
    model = Product  # Assuming you have a Product model
    template_name = "shop/newArrivals.html"
    context_object_name = "data"
    def get_queryset(self):
        # Order by the date_added field in descending order (most recent first)
        return Product.objects.order_by('-pub_date')[:10]

class Boys(ListView):
    model = Product  # Assuming you have a Product model
    template_name = "shop/boys.html"
    context_object_name = "data"
    def get_queryset(self):
        # Order by the date_added field in descending order (most recent first)
        return Product.objects.filter(category = "boys")

class girls(ListView):
    model = Product  # Assuming you have a Product model
    template_name = "shop/girls.html"
    context_object_name = "data"
    def get_queryset(self):
        # Order by the date_added field in descending order (most recent first)
        return Product.objects.filter(category = "girls")

class Electronics(ListView):
    model = Product  # Assuming you have a Product model
    template_name = "shop/Electronics.html"
    context_object_name = "data"
    def get_queryset(self):
        # Order by the date_added field in descending order (most recent first)
        return Product.objects.filter(category = "Electronics")

class Accessories(ListView):
    model = Product  # Assuming you have a Product model
    template_name = "shop/Accessories.html"
    context_object_name = "data"
    def get_queryset(self):
        # Order by the date_added field in descending order (most recent first)
        return Product.objects.filter(category = "accessories")



shop/templates/shop/Accessories.html
{% extends 'index.html' %}
        <!-- Navigation-->
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
         <!-- Header-->
        {% block content %}
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for product in data %}
                  <div class="col mb-5">
                      <a href="{% url 'product_detail' pk=product.pk %}">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.prod_name }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.prod_name}}</h5>
                                    <!-- Product price-->
                                    £{{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                      </a>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
        {% endblock %}

shop/templates/shop/Electronics.html
{% extends 'index.html' %}
        <!-- Navigation-->
        <!-- Header-->
        {% block content %}
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
         <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for product in data %}
                  <div class="col mb-5">
                      <a href="{% url 'product_detail' pk=product.pk %}">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.prod_name }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.prod_name}}</h5>
                                    <!-- Product price-->
                                    £{{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                      </a>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
        {% endblock %}

shop/templates/shop/boys.html
{% extends 'index.html' %}
        <!-- Navigation-->
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
         <!-- Header-->
        {% block content %}
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for product in data %}
                  <div class="col mb-5">
                      <a href="{% url 'product_detail' pk=product.pk %}">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.prod_name }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.prod_name}}</h5>
                                    <!-- Product price-->
                                    £{{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                      </a>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
        {% endblock %}

shop/templates/shop/checkout.html
{% extends 'index.html' %}

{% block content %}
    <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
         
  <section class="bg-light py-5">
    <div class="container">
      <div class="row">
          <div class="col-xl-8 col-lg-8 mb-4">
          <!-- Checkout -->
          <form method="post" id="user_address">{% csrf_token %}

            <div class="card shadow-0 border">
                <div class="p-4">
                    <h5 class="card-title1 mb-3">Guest checkout</h5>
                    <div class="row">
                        <div class="col-6 mb-3">
                            <p class="mb-0">First name</p>
                            <div class="form-outline">
                                <input type="text" id="id_firstname" name="firstname" placeholder="Type here" class="form-control" required />
                            </div>
                        </div>
        
                        <div class="col-6">
                            <p class="mb-0">Last name</p>
                            <div class="form-outline">
                                <input type="text" id="id_lastname" name="lastname" placeholder="Type here" class="form-control" required />
                            </div>
                        </div>
        
                        <div class="col-6 mb-3">
                            <p class="mb-0">Phone</p>
                            <div class="form-outline">
                                <input type="tel" id="id_phone" name="phone" class="form-control"  required/>
                            </div>
                        </div>
        
                        <div class="col-6 mb-3">
                            <p class="mb-0">Email</p>
                            <div class="form-outline">
                                <input type="email" id="id_email" name="email" placeholder="example@gmail.com" class="form-control" required />
                            </div>
                        </div>
                    </div>
        
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault"  />
                        <label class="form-check-label" for="flexCheckDefault">Keep me up to date on news</label>
                    </div>
        
                    <hr class="my-4" />
        
                    <h5 class="card-title1 mb-2">Shipping info</h5>
        
                    <div class="row mb-3">
                        <!-- Your radio button code remains unchanged -->
                    </div>
        
                    <div class="row">
                        <div class="col-sm-8 mb-3">
                            <p class="mb-0">Address</p>
                            <div class="form-outline">
                                <input type="text" id="id_address" name="address" placeholder="Type here" class="form-control" required />
                            </div>
                        </div>
        
                        <div class="col-sm-4 mb-3">
                            <p class="mb-0">City</p>
                            <select id="id_city" name="city" class="form-select">
                                <option value="1">New York</option>
                                <option value="2">Moscow</option>
                                <option value="3">Samarqand</option>
                            </select>
                        </div>
        
                        <div class="col-sm-4 mb-3">
                            <p class="mb-0">House</p>
                            <div class="form-outline">
                                <input type="text" id="id_house" name="house" placeholder="Type here" class="form-control" required />
                            </div>
                        </div>
        
                        <div class="col-sm-4 col-6 mb-3">
                            <p class="mb-0">Postal code</p>
                            <div class="form-outline">
                                <input type="text" id="id_postalcode" name="postalcode" class="form-control" required />
                            </div>
                        </div>
        
                        <div class="col-sm-4 col-6 mb-3">
                            <p class="mb-0">Zip</p>
                            <div class="form-outline">
                                <input type="text" id="id_zip" name="zip" class="form-control" required/>
                            </div>
                        </div>
                    </div>
        
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault1" />
                        <label class="form-check-label" for="flexCheckDefault1">Save this address</label>
                    </div>
        
                    <div class="mb-3">
                        <p class="mb-0">Message to seller</p>
                        <div class="form-outline">
                            <textarea id="id_message_to_seller" name="message_to_seller" class="form-control" rows="2"></textarea>
                        </div>
                    </div>
        
                    <div class="float-end">
                        <button class="btn btn-light border">Cancel</button>
                        <a href="{% url 'payment' %}"><button class="btn btn-success shadow-0 border">Continue</button></a>
                    </div>
                </div>
            </div>
        </form>
        
            <!-- Checkout -->
          </div>
        <div class="col-xl-4 col-lg-4 d-flex justify-content-center justify-content-lg-end">
          <div class="ms-lg-4 mt-4 mt-lg-0" style="max-width: 320px;">
            <h6 class="mb-3">Summary</h6>
            <div class="d-flex justify-content-between">
              <p class="mb-2">Total price:</p>
              <p class="mb-2">{{totalPrice}}</p>
            </div>
            <div class="d-flex justify-content-between">
              <p class="mb-2">Discount:</p>
              <p class="mb-2 text-danger">- $0.00</p>
            </div>
            <div class="d-flex justify-content-between">
              <p class="mb-2">Shipping cost:</p>
              <p class="mb-2">+ $10.00</p>
            </div>
            <hr />
            <div class="d-flex justify-content-between">
              <p class="mb-2">Total price:</p>
              <p class="mb-2 fw-bold">{{ totalPrice|add:10 }}</p>
            </div>
  
            <div class="input-group mt-3 mb-4">
              <input type="text" class="form-control border" name="" placeholder="Promo code" />
              <button class="btn btn-light text-primary border">Apply</button>
            </div>
  
            <hr />
            <h6 class="text-dark my-4">Items in cart</h6>
  
            {% for item in data %}
            <div class="d-flex align-items-center mb-4">
                <div class="me-3 position-relative">
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge-secondary">
                        {{ item.quantity }}
                    </span>
                    <img src="{{ item.image }}" style="height: 96px; width: 96px;" class="img-sm rounded border" />
                </div>
                <div class="">
                    <a href="#" class="nav-link">
                        {{ item.product_name }} <br />
                    </a>
                    <div class="price text-muted">Total: ${{ item.total|floatformat:2 }}</div>
                </div>
            </div>
        {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <!-- Footer -->
{% endblock %}

shop/templates/shop/girls.html
{% extends 'index.html' %}
        <!-- Navigation-->
        <!-- Header-->
        {% block content %}
        <a href="{% url 'ShopHome' %}"><i  style="color: rgb(0, 0, 0); position: relative; left: 2vw ;top: 10px ; cursor: pointer; ;font-size: 2rem ;border: 1px solid rgb(255, 255, 255);" class="fa-solid fa-arrow-left"></i> <!-- Section--></a>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for product in data %}
                  <div class="col mb-5">
                      <a href="{% url 'product_detail' pk=product.pk %}">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.prod_name }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.prod_name}}</h5>
                                    <!-- Product price-->
                                    £{{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                      </a>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
        {% endblock %}

shop/templates/shop/login.html
{% extends 'index.html' %}

{% block content %}
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="card col-md-6">
            <div class="card-body">
                <h2 class="text-center mb-4">Login</h2>
                <form method="post" style="align-items: center; width: 100; display: flex; flex-direction: column; align-items: center;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block mt-3">Log in</button>
                </form>
                <div class="text-center mt-3">
                    <small>Don't have an account? <a href="{% url 'signup' %}">Sign up here</a></small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/logout.html
{% extends 'index.html' %}

{% block content %}
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="card col-md-6">
            <div class="card-body">
                <h2 class="text-center mb-4">Logout</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block mt-3">confirm</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/signup.html
{% extends 'index.html' %}

{% block content %}
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="card col-md-6">
            <div class="card-body">
                <h2 class="text-center mb-4">Sign Up</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block mt-3">Sign Up</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}